# Generated by Django 4.2.28 on 2026-02-18 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(help_text='The prompt template text. Use {variable} for placeholders.')),
                ('category', models.CharField(choices=[('coding', 'Coding'), ('writing', 'Writing'), ('analysis', 'Analysis'), ('debug', 'Debug'), ('general', 'General'), ('custom', 'Custom')], default='general', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Public prompts are visible to all users.')),
                ('is_system', models.BooleanField(default=False, help_text='System prompts cannot be deleted by users.')),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_count', '-created_at'],
                'unique_together': {('user', 'slug')},
            },
        ),
    ]
